### PR TITLE
About us mobile

### PR DESCRIPTION
**Pull request by mxinburritos**

### CODE REVIEW

**Review by ayush-goyal — CHANGES_REQUESTED** [review]
Can you update all your spacings from 4 to 2 for all the files? It's hard to tell what exactly you changed since there are so many changes. Will review again after you do this.

**Comment by mxinburritos** [comment]
Oops, will do that real quick

**Comment by 1ntEgr8** [comment]
we'll need to change the images (they are currently hex shaped, we'll need rectangular ones so that they render correctly).

otherwise lgtm

merging it in

**Comment by 1ntEgr8** [comment]
actually, @mxinburritos  can you resolve the merge conflict? Feel free to merge after that

**Comment by ayush-goyal** [comment]
I got it fixed

**Comment by mxinburritos** [comment]
thx appreciate it!

**Pull request merged**
